---
- hosts: all
  vars:
    ansible_host_key_checking: false
  vars_files:
    - vars/linux.yml
  remote_user: "{{ansible_user}}"
  gather_facts: False
  tasks:
    - name: Remove if executable present on Local Machine
      shell: chdir=/tmp {{ item }}
      with_items:
      - rm -f vsp_install_vm.sh
      when: lfr_ip is defined
      ignore_errors: true
      delegate_to: 127.0.0.1
      args:
        warn: false
    - name: Download Virsec ASI Installables
      get_url:
        url: http://{{ lfr_ip }}/vsp/vsp_install_vm.sh
        dest: /tmp
        mode: '0755'
      when: lfr_ip is defined
      ignore_errors: true
      delegate_to: 127.0.0.1
    - name: Remove if executable present on Remote Machine
      shell: chdir=/home/virsec/ {{ item }}
      with_items:
      - rm -f vsp_install_vm.sh
      args:
          warn: false
      async: 30
      poll: 5
      become: true
      when: lfr_ip is defined
      ignore_errors: true
    - name: Copy Auto Registration Package
      command: sshpass -p {{ansible_password}} scp -o StrictHostKeyChecking=no {{ item }} {{ansible_user}}@{{inventory_hostname}}:/home/virsec/
      with_fileglob:
      - "/tmp/vsp_install_vm.sh"
      delegate_to: 127.0.0.1
      when: lfr_ip is defined
      ignore_errors: true
      args:
        warn: false
    - name: Change permission
      shell: chdir=/home/virsec/ {{ item }}
      with_items:
      - chmod 755 vsp_install_vm.sh
      become: true
      async: 40
      poll: 5
      when: lfr_ip is defined
      ignore_errors: true
      args:
        warn: false
    - name: Install Virsec ASI
      shell: chdir=/home/virsec/ {{ install_var }}
      args:
          executable: /bin/bash
          warn: false
      become: true
      when: lfr_ip is defined
      tags:
      - application


